### ISSUE TITLE
Document Tracking per Document: No results was displayed when searching for a record

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#64]
Pre-condition:
- There should be an existing filed and declared records in the RM site
Steps to replicate:

1. Login as admin.
2. Go to reports, select document tracking and select per document.
3. Enter the name of the record to be searched and enter

Actual result: No result was displayed even if user used asterisk before and after the keyword.

Expected result: Search result should display the records relevant to the search keyword.

Note: I used the latest commit no. cfb3a06
![image](https://cloud.githubusercontent.com/assets/7791554/10878084/513c3828-8186-11e5-8406-504fa603eb74.png)

**Comment by emarino0411** [comment]
Does this module search for Documents only?

**Comment by emarino0411** [comment]
I only have two document with the name status report but when I used the keyword "stat", no results were found. But when I used *e*, all documents were displayed. 

Document Names: Status Report - Oct 19-23 2015.docx and Status Report - Oct 19-23 2015-1.docx

If you use "stat" as search parameter, then document searching will search for filenames with only "stat" and not "status". Document searching does not automatically add * at the end. However, if you search for "status" then the documents will be displayed because it will match the first filename "Status".

For the *e*, it will display all records because all the documents contain e within the file name. Please note that the * before and after indicates that whatever characters will be before and after as long as the filename contains "e".

I think the document searching is working well.

**Comment by barbacenasmc** [comment]
Thanks Ms. May. This issue can no longer be replicated. I'm closing this issue now.
